#!/bin/sh

if [ -f ~/.bash_profile ]
then
  echo "moving ~/.bash_profile to ~/.backup_bash_profile # delete it at your convenience"
  backup_name=~/.backup_bash_profile`date +%s`
  touch $backup_name
  mv ~/.bash_profile $backup_name
fi
touch ~/.bash_profile

# build path for sh
echo "#!`which sh`" >> ~/.bash_profile; echo "."
cat paths           >> ~/.bash_profile; echo "."
cat development     >> ~/.bash_profile; echo "."
cat aliases         >> ~/.bash_profile; echo "."
cat environment     >> ~/.bash_profile; echo "."
cat prompt          >> ~/.bash_profile; echo "."

echo "Installation complete."